<a href="https://colab.research.google.com/github/yashc24/workshop/blob/main/numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## ***1. Import numpy::***

In [ ]:
import numpy as np

### ***2. Creating numpy as array::***

In [ ]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
a = np.array([3,4,2,5,7])
a

array([3, 4, 2, 5, 7])

In [ ]:
#2D and 3D
b = np.array([[2,3],[5,7]])
print(b)

[[2 3]
 [5 7]]


In [ ]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
a = np.array([[[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]]])
print(a)

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]

  [[ 9 10]
   [11 12]]]]


In [ ]:
a = np.array([1,2,3,4,5],dtype=float)
print(a)


[1. 2. 3. 4. 5.]


In [ ]:
b =np.array([1,2,3,4,5],dtype=complex)
print(b)
print(b.dtype)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]
complex128


In [ ]:
b =np.array([1,2,3,4,5],dtype=np.uint8)
print(b)
print(b.dtype)

[1 2 3 4 5]
uint8


In [ ]:
x = np.arange(15,60,4)
x

array([15, 19, 23, 27, 31, 35, 39, 43, 47, 51, 55, 59])

In [ ]:
# with reshape
y = np.arange(12).reshape(2,2,3)        #(layer,row,coloumn)and their multiply should be 12
y

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [ ]:
y = np.arange(12).reshape(4,3)        #(layer,row,coloumn)and their multiply should be 12
y

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### ***np.ones and np.zeros***

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#np.random
np.random.random((3,4))

array([[0.36078465, 0.32101802, 0.65989073, 0.07428198],
       [0.25786604, 0.76723503, 0.35818674, 0.75288229],
       [0.96721063, 0.01525966, 0.11156483, 0.75950785]])

In [ ]:
np.random.radint(2,10,4)

AttributeError: module 'numpy.random' has no attribute 'radint'

In [ ]:
#np.linspace
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [ ]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## ***4.Attributes of Arrays::***

In [ ]:
a1 = np.array([3,4,2,5,7])


In [ ]:
a1.ndim

1

In [ ]:
a1.shape

(5,)

In [ ]:
a1.size

5

In [ ]:
a1.dtype

dtype('int64')

In [ ]:
a1.itemsize

8

In [ ]:
a1.nbytes

40

In [ ]:
a2 = np.array([[2,3],[5,7]])


In [ ]:
a2.ndim

2

In [ ]:
a2.shape

(2, 2)

In [ ]:
a2.size

4

In [ ]:
a2.dtype

dtype('int64')

In [ ]:
a2.itemsize

8

In [ ]:
a2.nbytes

32

In [ ]:
a3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])


In [ ]:
a3.ndim

3

In [ ]:
a3.shape

(2, 2, 2)

In [ ]:
a3.size

8

In [ ]:
a3.dtype

dtype('int64')

In [ ]:
a3.itemsize

8

In [ ]:
a3.nbytes

64

### ***5.Changing Datatypes/Typecasting::***

In [ ]:
a3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
a3.astype(np.int32)
a3 = a3.astype(np.float64).dtype

In [ ]:
a3

dtype('float64')

## ***6. Array Operations::***

In [ ]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b = np.arange(12,24).reshape(3,4)
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### ***scalar operation***

In [ ]:
# arithmatic
a+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [ ]:
a-1

array([[-1,  0,  1,  2],
       [ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [ ]:
a*4

array([[ 0,  4,  8, 12],
       [16, 20, 24, 28],
       [32, 36, 40, 44]])

In [ ]:
a/2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [ ]:
a**3

array([[   0,    1,    8,   27],
       [  64,  125,  216,  343],
       [ 512,  729, 1000, 1331]])

In [ ]:
a//2

array([[0, 0, 1, 1],
       [2, 2, 3, 3],
       [4, 4, 5, 5]])

In [ ]:
# relational
a==10

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True, False]])

In [ ]:
a==15

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

### ***vector operation***

In [ ]:
# arithmatic
a+b

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [ ]:
a**b

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

In [ ]:
a//b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
a-b

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

### ***log and exponent***

In [ ]:
a1 = np.array([[1,2],[2,3]])
a1

array([[1, 2],
       [2, 3]])

In [ ]:
a1 = np.array([[1,2],[2,3]])
np.exp(a1)

array([[ 2.71828183,  7.3890561 ],
       [ 7.3890561 , 20.08553692]])

In [ ]:
a1 = np.array([[1,2],[2,3]])
np.log(a1)

array([[0.        , 0.69314718],
       [0.69314718, 1.09861229]])

## ***round,floor,ceil***

In [ ]:
a1 = np.array([[3.44,5.9],[4.67,8.99]])
np.round(a1)

array([[3., 6.],
       [5., 9.]])

In [ ]:
a1 = np.array([[3.44,5.9],[4.67,8.99]])
np.floor(a1)

array([[3., 5.],
       [4., 8.]])

In [ ]:
a1 = np.array([[3.44,5.9],[4.67,8.99]])
np.ceil(a1)

array([[4., 6.],
       [5., 9.]])

# ***iterating***

In [ ]:
a1 = np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]])
a1

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [ ]:
for i in a1:
  print(i)

[[1 2 3]]
[[4 5 6]]
[[7 8 9]]


In [ ]:
for i in np.nditer(a1):
  print(i)

1
2
3
4
5
6
7
8
9


In [ ]:
np.ravel(a1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# ***Slicing***

In [ ]:
a1[2:5:2]

array([[[7, 8, 9]]])

In [ ]:
a1[0:2,1::2]

array([], shape=(2, 0, 3), dtype=int64)

In [ ]:
a1[0,:]

array([[1, 2, 3]])